### ISSUE TITLE
output

### ISSUE THREAD

**Issue by SreenijaK** [keighrim/kaldi-yesno-tutorial#4]
In step4 I used the following command

steps/decode.sh exp/mono/graph  /home/test/kaldi_test/kaldi-yesno-tutorial/data/test_yesno exp/mono/decode

it gave following output:
decode.sh: feature type is delta
steps/diagnostic/analyze_lats.sh --cmd run.pl exp/mono/graph exp/mono/decode
steps/diagnostic/analyze_lats.sh: see stats in exp/mono/decode/log/analyze_alignments.log
Overall, lattice depth (10,50,90-percentile)=(1,1,2) and mean=1.1
steps/diagnostic/analyze_lats.sh: see stats in exp/mono/decode/log/analyze_lattice_depth_stats.log

How do i see the predicted text for the test data?

**Comment by keighrim** [comment]
Hi 
This repository is design as a part of programming assignment of a course offered by Brandeis University. Getting the text result is actually the main part of the assignment, so unfortunately I can't post exact steps. but take a look at [this script](https://github.com/keighrim/kaldi-yesno-tutorial/blob/master/steps/get_ctm.sh). It will be helpful.
